# Generated by Django 4.1.3 on 2022-11-28 12:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
