# Generated by Django 4.1.3 on 2022-11-21 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='authapp.course'),
        ),
    ]
